import { Metadata } from "next";
import { Gilda_Display } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
import SmootScroll from "./components/scrollingComponents/SmootScroll";

const Gilda = Gilda_Display({
    weight: "400",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Home Page",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${Gilda.className} bg-black text-white`}>
                <SmootScroll>
                    <Header />
                    {children}
                </SmootScroll>
            </body>
        </html>
    );
}
